### ISSUE TITLE
Invalid header name b'X-Qlik-Virtual-Proxy-Prefix:'

### ISSUE THREAD

**Issue by RobWunderlich** [rafael-sanz/qsAPI#1]
Hi Rafael, I'm receiving an Invalid Header error from http client.py:

File "C:**\AppData\Local\Programs\Python\Python35-32\lib\http\client.py", line 1074, in putheader raise ValueError('Invalid header name %r' % (header,)) ValueError: Invalid header name b'X-Qlik-Virtual-Proxy-Prefix:'

It seems to be complaining that the ":" char in the header is not valid. I've managed to work around this by modifying my local copy of client.py. However I can't do this on the other machines where I want to use it. Have you encountered this problem?

**Comment by rafael-sanz** [comment]
Hi Rob, like workaround just locate at row 143 and comment the next line:

> 'X-Qlik-Virtual-Proxy-Prefix:': self.vproxy,

This header is used by QPS and before was ignored in QRS, but in recent versions of Sense raise the error that you comment.

Give me a days and I expect commit an updated version.

Regards

**Comment by RobWunderlich** [comment]
Thanks! That did the trick. I'll let you close this when you commit.

**Comment by rafael-sanz** [comment]
Fixed since version 1.1
