### ISSUE TITLE
QRS instantiation doesnt work on Linux

### ISSUE THREAD

**Issue by philmorepunk87** [rafael-sanz/qsAPI#9]
I have setup a basic call to QRS and it works well on windows:
qrs=qsAPI.QRS(proxy='https://qlik.agilent.com', user={'userDirectory': 'AGILENT',
                                                          'userID': 'user',
                                                          'password': 'pw})

This works perfectly fine and I can then use the class with no issues.

However if I go to RedHat and run the same exact code with the same version of the library, I get a JSON decode error:
File "<stdin>", line 3, in <module>
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/qsAPI/_interfaces.py", line 87, in __init__
    self.VERSION_SERVER=self.getServerVersion()
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/qsAPI/_interfaces.py", line 138, in getServerVersion
    return _lv(self.driver.call('GET', '/qrs/about').json().get('buildVersion'))
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by philmorepunk87** [comment]
I am going to pull this down, I am fairly certain is an issue with Authentication and not an issue with the API itself

**Comment by xmatthias** [comment]
I'm using this successfully on a centos 7 system (which is basically a Red hat system).

best make sure that you've got the ntlm dependencies installed ... "most likely" - that's the problem for authentication problems (or a wrong / missing `/etc/krb5.conf` configuration)

**Comment by rafael-sanz** [comment]
Hi, the error message is not relevant about is really happening but "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)" means the expected JSON is empty. And the operation is in the first connection to the server to retrieve the version, certainly could be a problem with the authentication.

**Comment by philmorepunk87** [comment]
Thanks both for the responses. Matthias was correct, it ended up being a dependency issue. Once I got that sorted out it runs fine now.
